### ISSUE TITLE
Question - Loading Modules and PS Sessions

### ISSUE THREAD

**Issue by stvpwrs** [Azure/azure-functions-powershell-worker#656] opened 2021-07-20 18:21 UTC
This is a general question. Is there any documentation on best practices for importing modules? Can modules be imported through the profile.ps1? Does each function call get its own session or can we hot cache the importing of a large module before a function runs?

**Comment by AnatoliB** [comment] 2021-07-20 20:51
@stvpwrs I will assume you are talking about importing modules into PowerShell sessions, not about installing them to the file system from the PowerShell Gallery etc. (the latter is covered by https://aka.ms/functions-powershell-managed-dependency).

You can import modules explicitly in profile.ps1. This is rarely required though, as you can also rely on the PowerShell module autoload feature: just invoke the command, and PowerShell will automatically figure out which module should be imported. Importing modules explicitly is helpful in some troubleshooting scenarios: for example, some modules must be imported in a certain order because of interdependencies. These situations are relatively rare. In general, importing modules explicitly in profile.ps1 (or any other PowerShell code) will work.

There is no guarantee on whether a function call will get its own brand new session or reuse an existing one. The general idea is that Functions will try to reuse an existing session if it is available (in this case, modules will not have to be reloaded). Depending on many factors (app content, workload, plan), Functions may decide to scale out and create more PowerShell sessions, or more PowerShell worker processes, or even more machine instances. As a result, each new PowerShell session will execute profile.ps1 exactly once (guaranteed). The rest depends on the module design: some modules actually contain code and state shared within the process, so only the PowerShell-level objects need to be initialized per session. But, strictly from the PowerShell perspective, each session will have to load the required modules, explicitly (Import-Module) or implicitly (autoload).

I hope this helps.

**Comment by stvpwrs** [comment] 2021-07-20 21:09
@AnatoliB thanks for the reply. Yes importing modules was what I was referring too. Ideally I would like to use `using module` to also import classes from a module. Using `#requires` or `using module` ensures it's loaded first or that the classes are loaded as well.

Different functions will never share a session through correct? 

My understanding is:
The profile.ps1 will get executed with each function, but within a function app run-function01 and run-function02 will never share a session, but multiple calls of run-function01 might share a session.

**Comment by AnatoliB** [comment] 2021-07-20 22:18
@stvpwrs _Function app_ is the boundary here, not individual _functions_. For the first function invocation, a PowerShell session is created, profile.ps1 gets executed in this session, and then the function code gets executed. When this invocation completes, the session returns to the pool. At this point, if you invoke another function _in the same function app_, this invocation _may_ get the existing session from this pool (in this case, profile.ps1 will not run again). If you need a guarantee that PowerShell sessions are not reused between two different _functions_, you need to move these functions to separate _function apps_.

**Comment by stvpwrs** [comment] 2021-07-21 12:33
@AnatoliB thanks again for the reply. This information was very helpful. Without the natural scoping of class it seems there would a decent chance of getting race conditions on a Function App that's calling several different PowerShell functions with them using the default `$Request` variable. 

If `$Request` isn't copied right away will referencing that potentially see a different `$Request` that has come in for a different function? 

It feels like the default template should be a PowerShell advanced function to provide some scoping.

**Comment by AnatoliB** [comment] 2021-07-21 16:38
@stvpwrs Are you talking about the `$Request` _parameter_? Parameters are naturally safe to use because every function invocation gets its own instance. Furthermore, PowerShell _variables_ are also safe because they belong to a PowerShell session. Sessions can be reused for multiple invocations, but not concurrently: every function invocation gets exactly one thread and one session assigned, and this one thread and one session remain reserved for this invocation exclusively until the invocation completes. Only after that, the session returns to the pool and can later be assigned to another invocation. As a result, there is no attempt to use the same variable from multiple threads concurrently. Of course, if you spawn your own threads, or your variable refers to a process-scoped object, you are on your own and should take care of synchronizing access. But, by default, the situation is simple.

**Comment by stvpwrs** [comment] 2021-07-21 17:40
@AnatoliB tremendous thanks for answering these questions. When sessions are returned to the pool for another invocation is it always for the same function or could another function get that session? It seems the threat of "polluting" variables or carrying over state is slim, but I'm trying to understand what should be coded defensively for that session reuse case.

So all sessions will always have `profile.ps1` run first, but it's possible that before it's disposed, the session will run be used to run another invocation without `profile.ps1` being run again. 

So if say all functions in a Function App need to import a particular module, then doing that import in `profile.ps1` will possibly save an import if that session is reused again because that import will carry over in the used session?

**Comment by AnatoliB** [comment] 2021-07-21 18:05
@stvpwrs The session pool is shared across the entire _function app_. Any session returned to the pool can be reused for running any _function_ within the same _function app_. Also, the worker performs some automatic cleanup before reusing sessions (such as removing all new global variables): https://github.com/Azure/azure-functions-powershell-worker/blob/b3983f3044cdbbc3f6dafadd7d7d82cc7ff6f34a/src/PowerShell/PowerShellManager.cs#L317
However, this is not a comprehensive cleanup, so you can expect some leftovers. For example, we don't try to unload modules (which seems to be a good thing in your case). If a module is imported into a session, it remains imported when the session is reused, regardless of whether this is the same function or not.
In any case, this cleanup does not involve running profile.ps1 again. Like I said, profile.ps1 is executed once per session, not once per function invocation. The situation you are describing ("before it's disposed, the session will run be used to run another invocation without profile.ps1 being run again") is not just possible, but it is expected and intentional by design. This is what profile.ps1 is for. If you need to execute code for each invocation, put it into the function (run.ps1), not profile.ps1.

**Comment by stvpwrs** [comment] 2021-07-21 19:50
@AnatoliB Thanks for all the time to answer these questions. I'm going to close the comment/issues out. This has been immensely helpful.

**Closed as completed** 2021-07-21 19:50 UTC
