### ISSUE TITLE
Managed Dependencies with Proxies do not work.

### ISSUE THREAD

**Issue by npachal** [Azure/azure-functions-powershell-worker#255] opened 2019-06-08 23:29 UTC
When deploying an Azure Function App with an ARM Template, when starting a function, a 500 error is generated:

_FailureException: Fail to install function app dependencies. Restarting the app may resolve the error. Error: 'No 'requirements.psd1' is found at the FunctionApp root folder: D:\home\site_

The function root folder should be D:\home\site\wwwroot

[powershellFunctionApp.txt](https://github.com/Azure/azure-functions-powershell-worker/files/3268997/powershellFunctionApp.txt)

**Comment by Francisco-Gamino** [comment] 2019-06-09 02:12
Hi @npachal , thank you for reporting this issue. Could you please provide a bit more information about your function app?

1) How did you created your function app? Did you use the Core Tools? or Visual Studio Code?
2) Are you using proxies in your function app? 
3) What is the time range when you got this failure? To which region did you deploy your app? Do you have the invocation id? I need the invocation id to try to figure out your function app name.

**Comment by npachal** [comment] 2019-06-09 04:07
Thank you for the reply. I'm using Dev Ops to deploy the function app (via a pipeline), but created it in VS Code. I am using a proxy in my function app to direct to a static page. The region is West US, and the invocation id is 67d069b4-2ac9-4081-ab12-447f07941ae7

**Comment by Francisco-Gamino** [comment] 2019-06-10 06:01
@npachal , 
Thank you for the function app information.
If you are using a proxy, then this issue is being caused by https://github.com/Azure/azure-functions-host/issues/4549. As soon as I have an ETA for fix, I will let you know.

**Comment by npachal** [comment] 2019-06-10 14:07
Thank you.

**Comment by anirudhgarg** [comment] 2019-06-11 22:21
Assigning to @Francisco-Gamino to do the work of making sure that PowerShell is working with proxies

**Comment by Francisco-Gamino** [comment] 2019-06-21 04:32
Hi @npachal : I will have a fix for this tomorrow. However, we need to wait for the next release of the Host (runtime) which is in about two weeks or so.

**Comment by npachal** [comment] 2019-06-21 13:13
Thank you

**Comment by Francisco-Gamino** [comment] 2019-07-11 17:03
Hello @npachal, this should be fixed now. Please let us know if you find any other issues. Thanks.

**Closed by Francisco-Gamino** 2019-07-11 17:03 UTC
