### ISSUE TITLE
Set-DurableCustomStatus doesn't exist on Azure Functions PaaS

### ISSUE THREAD

**Issue by TheGreggle** [Azure/azure-functions-powershell-worker#634] opened 2021-05-06 00:01 UTC
Attempting to call `Set-DurableCustomStatus` as per the example [here](https://github.com/Azure/azure-functions-powershell-worker/blob/dev/examples/durable/DurableApp/CustomStatusOrchestrator/run.ps1) on Azure PaaS.

On Azure PaaS, the error `The term 'Set-DurableCustomStatus' is not recognized as the name of a cmdlet, function, script file, or operable program.` occurs. The same issue was posted [here](https://docs.microsoft.com/en-us/answers/questions/295144/set-custom-context-in-azure-function-using-powersh.html)

In Azure, FUNCTIONS_WORKER_RUNTIME is set to powershell. FUNCTIONS_EXTENSION_VERSION is set to ~3. PowerShell Core Version is 7.0.

The PowerShell Worker code was updated here https://github.com/Azure/azure-functions-powershell-worker/pull/592 to support `Set-DurableCustomStatus`.

Locally, downloaded version [3.0.15584](https://github.com/Azure/azure-functions-host/releases/tag/v3.0.15584) and replaced the worker files in "C:\Program Files\Microsoft\Azure Functions Core Tools\workers\powershell". After this, `Set-DurableCustomStatus` works locally.

Is there a way to update Azure Functions PaaS to support the new code and `Set-DurableCustomStatus`?
If not, is there an ETA on when this may be available (preview or GA)?

Thanks

**Comment by AnatoliB** [comment] 2021-05-06 01:54
@TheGreggle To use this feature, you need Functions runtime 3.0.15584 or higher, and it may not be rolled out to your region yet. Please **restart your app** and check the version under Overview/Essentials in the Portal (you may need to wait for a few seconds for it to appear):

![image](https://user-images.githubusercontent.com/11563624/117230934-ff20a900-add2-11eb-94c8-d4a734752eef.png)

If you see anything lower than 3.0.15584, please wait for a few days. If you see 3.0.15584 or higher, and `Set-DurableCustomStatus` is still not recognized, please let us know.

**Comment by TheGreggle** [comment] 2021-05-06 02:52
@AnatoliB thanks for your quick response.

I didn't know that Runtime version was there. Very handy.

My function version is 3.0.15584.0 and in the Australia East region.
Is there anything else I can run to give you some more information?

**Comment by AnatoliB** [comment] 2021-05-06 05:37
@TheGreggle I was unable to reproduce the issue on 3.0.15584. If this still happens for you, could you please point us to the invocation logs by using [these instructions](https://github.com/Azure/azure-webjobs-sdk-script/wiki/Sharing-Your-Function-App-name-privately)? Could you please also share the entire source code of your orchestrator function?

**Comment by TheGreggle** [comment] 2021-05-06 10:29
@AnatoliB thanks again for your assistance. To be sure, and so I could send you a clean example, I deployed the unmodified [example](https://github.com/Azure/azure-functions-powershell-worker/blob/dev/examples/durable/DurableApp/CustomStatusOrchestrator/run.ps1) and it worked.

I then re-deployed my version (which was failing) and it worked. I think I was just unlucky, and version 3.0.15584 must have deployed whilst I was writing this up.

At least you taught me how to check the runtime version. Once again thank you for your help.

**Comment by AnatoliB** [comment] 2021-05-07 20:13
Closing for now, please let us know if it happens again

**Closed as completed by AnatoliB** 2021-05-07 20:13 UTC
Labels: feature:durable functions, Needs: Attention :wave:
