### ISSUE TITLE
Object Array received from HTTP response

### ISSUE THREAD

**Issue by Agazoth** [Azure/azure-functions-powershell-worker#216] opened 2019-05-09 13:42 UTC
When returning an array of objects in a HTTP response, only one object is returned. The first element of this object contains the array of the objects expected as response.

When returning elements like this in the Powershell Azure Function:
```powershell
Write-host $Users.Count
101
$status = [HttpStatusCode]::OK
Push-OutputBinding -Name Response -Value ([HttpResponseContext]@{
    StatusCode = $status
    Body = $Users
})
```
the following is received , when calling the webhook and storing the result in a variable called result:
```powershell
$result.count
1

$result[0].count
101
```
Ideally result should contain the objects. 

Reference: https://github.com/MicrosoftDocs/azure-docs/issues/30705

**Comment by JustinGrote** [comment] 2019-05-09 14:56
@Agazoth 
I couldn't reproduce. Are you sure your original "Users" array wasn't double wrapped in another array? 

Here's my test function:

```powershell
param (
    $Request,
    $TriggerMetadata
)

$testObject = @("Test Text","Test Text 2")

"Input Object Count: " + $testObject.count
"Input Object Type:" + $testObject.gettype()

"Object Table View"
"================="
$testObject | ft | out-string

Push-OutputBinding -Name Response -Value ([HttpResponseContext]@{
    Body = $testObject
})
```

"Raw" JSON Result from invoke-webrequest
```
> (iwr http://localhost:7071/api/Sandbox).content
[
  "Test Text",
  "Test Text 2"
]

```
Result from invoke-restmethod
```
> irm http://localhost:7071/api/Sandbox
Test Text
Test Text 2
[00:01.056] 
> (irm http://localhost:7071/api/Sandbox).count
2
[00:01.072] 
```
Functions Log
```
[5/9/2019 2:53:35 PM] OUTPUT: Input Object Count: 2
[5/9/2019 2:53:35 PM] OUTPUT: Input Object Type:System.Object[]
[5/9/2019 2:53:35 PM] OUTPUT: Object Table View
[5/9/2019 2:53:35 PM] OUTPUT: =================
[5/9/2019 2:53:35 PM] OUTPUT: Test Text
[5/9/2019 2:53:35 PM] Test Text 2
```

**Comment by Agazoth** [comment] 2019-05-09 17:17
Turns out this is only happens when I collect the result with the -OutVariable parameter. This seems to be a bug in Invoke-RestMethods OutVariable method:

```powershell
# PowerShell Azure Function:
using namespace System.Net

# Input bindings are passed in via param block.
param($Request, $TriggerMetadata)

$Response = 1..4 | foreach {
    [pscustomobject]@{
        Attribute1 = "Value$_"
        Atrribute2 = "Value$_"
        Attribute3 = "Value$_"
    }
}

$Response.count

# Associate values to output bindings by calling 'Push-OutputBinding'.
Push-OutputBinding -Name Response -Value ([HttpResponseContext]@{
    StatusCode = [HttpStatusCode]::OK
    Body = $Response
})

```
I execute the function like this:

```powershell
> irm -Uri $Uri -ov OutVar

Attribute1 Atrribute2 Attribute3
---------- ---------- ----------
Value1     Value1     Value1
Value2     Value2     Value2
Value3     Value3     Value3
Value4     Value4     Value4

> $OutVar.count
1

> $OutVar[0].count
4
```

This is the result in the log file:

```powershell

2019-05-09T16:51:28.685 [Information] Executing 'Functions.GetAzureADUser' (Reason='This function was programmatically called via the host APIs.', Id=b4351d77-d630-47d6-9e7a-123458b21ad6)
2019-05-09T16:51:28.921 [Information] OUTPUT: 4
2019-05-09T16:51:28.922 [Information] Executed 'Functions.GetAzureADUser' (Succeeded, Id=b4351d77-d630-47d6-9e7a-123458b21ad6)

```

If I run one of these:

```powershell
> irm -Uri $Uri | sv SetVar
> $Var = irm -Uri $Uri
> $SetVar.count
4
> $Var.count
4
```
And the objects are different:

```powershell
> $Var | gm


   TypeName: System.Management.Automation.PSCustomObject
Name        MemberType   Definition
----        ----------   ----------
Equals      Method       bool Equals(System.Object obj)
GetHashCode Method       int GetHashCode()
GetType     Method       type GetType()
ToString    Method       string ToString()
Atrribute2  NoteProperty string Atrribute2=Value1
Attribute1  NoteProperty string Attribute1=Value1
Attribute3  NoteProperty string Attribute3=Value1

> $SetVar | gm


   TypeName: System.Management.Automation.PSCustomObject
Name        MemberType   Definition
----        ----------   ----------
Equals      Method       bool Equals(System.Object obj)
GetHashCode Method       int GetHashCode()
GetType     Method       type GetType()
ToString    Method       string ToString()
Atrribute2  NoteProperty string Atrribute2=Value1
Attribute1  NoteProperty string Attribute1=Value1
Attribute3  NoteProperty string Attribute3=Value1

> $OutVar | gm


   TypeName: System.Object[]
Name           MemberType            Definition
----           ----------            ----------
Add            Method                int IList.Add(System.Object value)
Address        Method                System.Object&, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e Address(int )
Clear          Method                void IList.Clear()
Clone          Method                System.Object Clone(), System.Object ICloneable.Clone()
CompareTo      Method                int IStructuralComparable.CompareTo(System.Object other, System.Collections.IComparer comparer)
Contains       Method                bool IList.Contains(System.Object value)
CopyTo         Method                void CopyTo(array array, int index), void CopyTo(array array, long index), void ICollection.CopyTo(array array, int index)
Equals         Method                bool Equals(System.Object obj), bool IStructuralEquatable.Equals(System.Object other, System.Collections.IEqualityComparer comparer)
Get            Method                System.Object Get(int )
GetEnumerator  Method                System.Collections.IEnumerator GetEnumerator(), System.Collections.IEnumerator IEnumerable.GetEnumerator()
GetHashCode    Method                int GetHashCode(), int IStructuralEquatable.GetHashCode(System.Collections.IEqualityComparer comparer)
GetLength      Method                int GetLength(int dimension)
GetLongLength  Method                long GetLongLength(int dimension)
GetLowerBound  Method                int GetLowerBound(int dimension)
GetType        Method                type GetType()
GetUpperBound  Method                int GetUpperBound(int dimension)
GetValue       Method                System.Object GetValue(Params int[] indices), System.Object GetValue(int index), System.Object GetValue(int index1, int index2), System.Object GetValue(int i…
IndexOf        Method                int IList.IndexOf(System.Object value)
Initialize     Method                void Initialize()
Insert         Method                void IList.Insert(int index, System.Object value)
Remove         Method                void IList.Remove(System.Object value)
RemoveAt       Method                void IList.RemoveAt(int index)
Set            Method                void Set(int , System.Object )
SetValue       Method                void SetValue(System.Object value, int index), void SetValue(System.Object value, int index1, int index2), void SetValue(System.Object value, int index1, int…
ToString       Method                string ToString()
Item           ParameterizedProperty System.Object IList.Item(int index) {get;set;}
Count          Property              int Count {get;}
IsFixedSize    Property              bool IsFixedSize {get;}
IsReadOnly     Property              bool IsReadOnly {get;}
IsSynchronized Property              bool IsSynchronized {get;}
Length         Property              int Length {get;}
LongLength     Property              long LongLength {get;}
Rank           Property              int Rank {get;}
SyncRoot       Property              System.Object SyncRoot {get;}
```
I guess this issue should be moved to PowerShell/PowerShell instead.

**Comment by Agazoth** [comment] 2019-05-09 17:25
Seems to be the same in both Windows PowerShell and PowerShell Core:

```powershell
> irm 'https://jsonplaceholder.typicode.com/posts' | gm


   TypeName: System.Object[]

Name           MemberType            Definition
----           ----------            ----------
Count          AliasProperty         Count = Length
Add            Method                int IList.Add(System.Object value)
Address        Method                System.Object&, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 Address(int )
Clear          Method                void IList.Clear()
Clone          Method                System.Object Clone(), System.Object ICloneable.Clone()
CompareTo      Method                int IStructuralComparable.CompareTo(System.Object other, System.Collections.IComparer comparer)
Contains       Method                bool IList.Contains(System.Object value)
CopyTo         Method                void CopyTo(array array, int index), void CopyTo(array array, long index), void ICollection.CopyTo(array array, int index)
Equals         Method                bool Equals(System.Object obj), bool IStructuralEquatable.Equals(System.Object other, System.Collections.IEqualityComparer comparer)
Get            Method                System.Object Get(int )
GetEnumerator  Method                System.Collections.IEnumerator GetEnumerator(), System.Collections.IEnumerator IEnumerable.GetEnumerator()
GetHashCode    Method                int GetHashCode(), int IStructuralEquatable.GetHashCode(System.Collections.IEqualityComparer comparer)
GetLength      Method                int GetLength(int dimension)
GetLongLength  Method                long GetLongLength(int dimension)
GetLowerBound  Method                int GetLowerBound(int dimension)
GetType        Method                type GetType()
GetUpperBound  Method                int GetUpperBound(int dimension)
GetValue       Method                System.Object GetValue(Params int[] indices), System.Object GetValue(int index), System.Object GetValue(int index1, int index2), System.Object GetValue(int index1, int index2, int index...
IndexOf        Method                int IList.IndexOf(System.Object value)
Initialize     Method                void Initialize()
Insert         Method                void IList.Insert(int index, System.Object value)
Remove         Method                void IList.Remove(System.Object value)
RemoveAt       Method                void IList.RemoveAt(int index)
Set            Method                void Set(int , System.Object )
SetValue       Method                void SetValue(System.Object value, int index), void SetValue(System.Object value, int index1, int index2), void SetValue(System.Object value, int index1, int index2, int index3), void S...
ToString       Method                string ToString()
Item           ParameterizedProperty System.Object IList.Item(int index) {get;set;}
IsFixedSize    Property              bool IsFixedSize {get;}
IsReadOnly     Property              bool IsReadOnly {get;}
IsSynchronized Property              bool IsSynchronized {get;}
Length         Property              int Length {get;}
LongLength     Property              long LongLength {get;}
Rank           Property              int Rank {get;}
SyncRoot       Property              System.Object SyncRoot {get;}


PS C:\Users\AxelBøgAndersen> irm 'https://jsonplaceholder.typicode.com/posts' | sv test; $test | gm


   TypeName: System.Management.Automation.PSCustomObject

Name        MemberType   Definition
----        ----------   ----------
Equals      Method       bool Equals(System.Object obj)
GetHashCode Method       int GetHashCode()
GetType     Method       type GetType()
ToString    Method       string ToString()
body        NoteProperty string body=quia et suscipit...
id          NoteProperty int id=1
title       NoteProperty string title=sunt aut facere repellat provident occaecati excepturi optio reprehenderit
userId      NoteProperty int userId=1

```

Get-Member handles the result from irm different then Set-Variable

**Comment by Agazoth** [comment] 2019-05-09 17:29
Hmm, stupid me - I guess: https://github.com/PowerShell/PowerShell/issues/9381

**Comment by TylerLeonhardt** [comment] 2019-05-09 19:12
No worries! Glad we got to the bottom of it 😊

Closing since it's not an issue with Azure Functions. Let me know if you feel otherwise.

**Closed by TylerLeonhardt** 2019-05-09 19:12 UTC
