### ISSUE TITLE
$env variables are being reverted to strings

### ISSUE THREAD

**Issue by rdbartram** [Azure/azure-functions-powershell-worker#215] opened 2019-05-08 20:31 UTC
I haven't tested this from local install of the runtime but within azure I have a super strange bug. If I created a $env variable and assign it a hashtable for example. When call it immediately afterwards, it is a string and no longer a hashtable. I tried the same with a dictionary and somehow I always endup with strings. As soon as I change the scope to either global, normal or script...everything works fine. Not sure where to even start looking for this bug in the code but if you need any extra info, let me know.

**Comment by JustinGrote** [comment] 2019-05-08 21:10
Hi @rdbartram,

Environment variables are not Powershell variables, they are an operating system concept and they are always strings. This is not specific to Azure Functions, try running this in your local powershell console:

~> $env:myTestVariable = @{test=3;test2=5}
~> $env:myTestVariable
System.Collections.Hashtable

$env: is a special syntax which reads the environment variable from the env: PSDrive. It is not the same as $GLOBAL:variable or $LOCAL:variable

Hope that helps, you can probably close this as "not a bug"

**Comment by TylerLeonhardt** [comment] 2019-05-08 23:06
Thanks, @JustinGrote! That is correct. Environment variables are always strings. I'll close this now but if you have any questions, please let me know!

**Closed by TylerLeonhardt** 2019-05-08 23:06 UTC

**Comment by rdbartram** [comment] 2019-05-10 06:50
😳...how have I only noticed this for the first time, 7 years after using powershell. Thanks  for the info though.
