### ISSUE TITLE
Could not attach to process with CustomPipeName: 'AzureFunctionsPSWorker'

### ISSUE THREAD

**Issue by nnekaede** [Azure/azure-functions-powershell-worker#368] opened 2019-12-09 14:00 UTC
I have a PowerShell Function App which I would like to build and test locally. Previously, I could run locally with no issue, but now this is no the case. When I type `func host start` or F5, I am prompted with the following error:

> You must have the Azure Functions Core Tools installed to debug your local functions.

When I click install, I get the following error:

> Could not attach to process with CustomPipeName: 'AzureFunctionsPSWorker'

*** I have opened this issue in the vscode-azurefunctions repo as well. As I am not sure who can help me: https://github.com/microsoft/vscode-azurefunctions/issues/1744#issue-534941282

**Comment by anirudhgarg** [comment] 2019-12-09 17:57
@nnekaede thanks for reporting. In the flow that you describe above are you using VSCode to build and test ?

**Comment by nnekaede** [comment] 2019-12-10 18:22
Yes I am

**Comment by AnatoliB** [comment] 2019-12-10 20:17
Thank you @nnekaede, could you please share your Azure Functions Core Tools version (`func --version`)?

**Comment by AnatoliB** [comment] 2019-12-10 21:56
@nnekaede Also, could you please check if your logs contain messages like this:

```
[timestamp] The specified framework 'Microsoft.NETCore.App', version '2.2.0' was not found.
[timestamp]   - The following frameworks were found:
[timestamp]       2.1.12 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
[timestamp]       3.0.1 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
```

If they do, please check if you have .NET Core 2.2 installed on your machine and if not install it and try again.

**Comment by nnekaede** [comment] 2019-12-12 15:29
Heres the thing. I have installed Azure Functions Core Tools v2, specifically 2.7.1948. I have done so using this command: `npm install -g azure-functions-core-tools`. But when I press F5 it still prompts me to install Azure Functions Core Tools.

So I click install. From there it installs the same exact package and gives me the error `Could not attach to process with CustomPipeName: 'AzureFunctionsPSWorker`. It then opens the launch.json file and the terminal says:
```
Executing task: func host start <

/usr/bin/bash: func: command not found
The terminal process terminated with exit code: 127

Terminal will be reused by tasks, press any key to close it.
```
I do not see anything in the logs about 'Microsoft.NETCore.App', version '2.2.0'

**Comment by nnekaede** [comment] 2019-12-12 15:30
The json file I mention above says the following:

`{
    "version": "0.2.0",
    "configurations": [
        
        {
            "name": "Attach to PowerShell Functions",
            "type": "PowerShell",
            "request": "attach",
            "customPipeName": "AzureFunctionsPSWorker",
            "runspaceId": 1,
            "preLaunchTask": "func: host start"
        }
    ]
}`

**Comment by Francisco-Gamino** [comment] 2019-12-12 20:00
Hello @nnekaede, I was able to repro this issue. 

To fix this, could you please try the following?
* Reinstall the latest version of the Azure Functions extension for VSCode
* Install the latest version of .Net Core **2.1** and **2.2**
* Install the latest version of the Core Tools. Based on your previous comment above, it looks like the Core Tools is not being added to your path. This should be resolve if you reinstall the Core Tools. After the installation has completed, open PowerShell and run `get-command func`. If PowerShell is not able to find it, then we need to manually add the path to the Core Tools to the `Path` variable.

**Note: After installing the Core Tools, please restart PowerShell and VSCode.**

Lastly, could you please send me the following outputs to double check the version of the Core Tools and .Net Core:
```
PS C:\> func --version
2.7.1948
```
```
PS C:\> dotnet --info                                                                                                                                                                                .NET Core SDK (reflecting any global.json):
 Version:   2.2.207
 Commit:    f7b16a2cd5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.207\

Host (useful for support):
  Version: 2.2.8
  Commit:  b9aa1abc51

.NET Core SDKs installed:
  2.1.607 [C:\Program Files\dotnet\sdk]
  2.2.207 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
PS C:\>                                                                                                                     
```
Thanks,
Francisco

**Comment by Francisco-Gamino** [comment] 2019-12-17 17:14
Hi @nnekaede, could you please let us know if installing the latest version of both .**Net Core 2.1** and **2.2** solve your issue? Thanks!

**Comment by nnekaede** [comment] 2019-12-18 21:25
Hi. I am sorry for the late reply.

I followed your steps. I reinstall azure functions vs code extension. I installed the .net core, and I installed azure core tools.

My .net is up to date:
```
PS C:\>  dotnet --info                                                                                                  
.NET Core SDK (reflecting any global.json):
 Version:   2.2.207
 Commit:    f7b16a2cd5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.207\

```
With regards to Azure Core Tools, I still have no luck.
```
PS C:\>  func --version                                                                                                 
func : The term 'func' is not recognized as the name of a cmdlet, function, script file, or operable program. Check
the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:2
+  func --version
+  ~~~~
    + CategoryInfo          : ObjectNotFound: (func:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

**Comment by Francisco-Gamino** [comment] 2019-12-18 21:46
Adding @ankitkumarr for FYI.

Hi @nnekaede. Are you installing the Core Tools via `npm`? Also, please install **.Net Core 2.1**. Lastly, what's your default shell in VSCode? Are you setting it to be `pwsh` (PowerShell)?

**Comment by nnekaede** [comment] 2019-12-19 17:09
Hi, @Francisco-Gamino I am installing Core Tools using npm specifically `npm install -g azure-functions-core-tools`.

My Default shell is Git Bash. But I also have Command Prompt, Powershell, Powershell Core (pwsh). When I am installing azure functions core tools I am using Powershell Integrated Console. 

I have installed both .net core 2.1 and 2.2
```
dotnet --info                                                                                                 
 .NET Core SDK (reflecting any global.json):
 Version:   2.2.207
 Commit:    f7b16a2cd5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.207\

Host (useful for support):
  Version: 2.2.8
  Commit:  b9aa1abc51

.NET Core SDKs installed:
  2.1.607 [C:\Program Files\dotnet\sdk]
  2.1.700 [C:\Program Files\dotnet\sdk]
  2.1.801 [C:\Program Files\dotnet\sdk]
  2.2.207 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
```

**Comment by Francisco-Gamino** [comment] 2019-12-20 18:52
Thank you @nnekaede for the additional information. Could you please try the following?

1) Open pswsh (PowerShell) and run `func --version`. Do you get an output here? If you do, then move to step 2. If you don't, then let me know and we'll fix this first.

![image](https://user-images.githubusercontent.com/12720858/71283990-87a1c500-2316-11ea-9917-289f9bd74e70.png)


2) Open VSCode --> Open your PowerShell function app --> Go to the `Terminal` window. Remove all shells from the drop down box. Then, add `pwsh` as the default shell. After this, go the `Terminal` window and run: `func`. You should see some output here. If you do, go to step 3.
3) Add `Wait-Debugger` in your `run.ps1` script and hit F5.

Your VSCode should look like this:
![image](https://user-images.githubusercontent.com/12720858/71283895-50cbaf00-2316-11ea-845e-dc7faf273d5e.png)

Thanks,
Francisco

**Comment by Francisco-Gamino** [comment] 2019-12-23 23:26
Hello @nnekaede, I am going to be out of the office for a couple of weeks, and I will not be able to look at this until I come back on 1/7/20.

Thanks,
Francisco

**Comment by nnekaede** [comment] 2020-01-06 14:16
Happy New Year. When I run` func --version`, I get an error.

`func : The term 'func' is not recognized as the name of a cmdlet, function, script file, or operable program.`

**Comment by Francisco-Gamino** [comment] 2020-01-06 22:47
Adding @ankitkumarr (for Core Tools)

Hello @nnekaede, Happy New Year to you as well. Are you getting the error above from running ` `pwsh`? If you are, it looks like you could not passed step 1. Are you available tomorrow Tuesday 1/7 for a 30 minute call? This way we can debug your environment via video call. I am available from 11:00-11:30 am and 1:00-3:00 pm Pacific Standard Time. Let me know. 

Hi @ankitkumarr, @nnekaede is installing the Core Tools via `npm`. However, it looks like the path to the Core Tools are not being added to the `PATH` variable. Is this a known issue?

Thanks,
Francisco

**Comment by nnekaede** [comment] 2020-01-07 18:16
Yes I get this error in Powershell. I can meet at 1:00 which is my 3 pm.

**Comment by Francisco-Gamino** [comment] 2020-01-07 18:26
Hi @nnekaede, I will send you a meeting request to the main email address in your profile. I will sync with you at 1 pm PST.

**Comment by nnekaede** [comment] 2020-01-07 18:36
nneka.ede@chevron.com

**Comment by Francisco-Gamino** [comment] 2020-01-07 18:41
Hi @nnekaede -- meeting invite updated.

**Comment by ankitkumarr** [comment] 2020-01-07 18:56
Hi @nnekaede,

In the meanwhile, would you mind -- 
1. Running `%AppData%\npm\func --version` and see if that works.
2. If above works, you'd want to add to your `PATH` environment variable `%AppData%\npm` value. Then it should work as expected.

**Comment by nnekaede** [comment] 2020-01-07 19:42
@ankitkumarr unfortunately this did not seem to work either.

**Comment by Francisco-Gamino** [comment] 2020-01-07 21:42
Hi @nnekaede, thanks for attending the video call today. I am glad we were able to resolve this issue.

In summary, we needed to add `%AppData%\npm\func` to the `PATH` variable and make `pwsh` the default shell in the `Terminal` window in VSCode. After this, the debugger in the Azure Functions extension worked as expected.

I will go ahead and close this. Please do not hesitate to reach out if you encounter any more issues.

Thanks,
Francisco

**Closed as completed by Francisco-Gamino** 2020-01-07 21:42 UTC
Labels: Needs: Attention :wave:

**Comment by Fabiano2** [comment] 2020-12-03 20:28
Hi

**Comment by Fabiano2** [comment] 2020-12-03 20:30
Hi, does someone know how to add %AppData%\npm\func to the path? I'm stuck in this problem.

**Comment by Francisco-Gamino** [comment] 2020-12-03 20:35
Hey @Fabiano2 -- The path to the Core Tools should be added automatically when you install the Core Tools. 

A couple of questions:
What version of the Core Tools are you using? 
How are you installing the Core Tools?

If the issue is with the Core Tools, please open a new issue here https://github.com/Azure/azure-functions-core-tools/issues and tag me on it. Thanks.

**Comment by Fabiano2** [comment] 2020-12-03 20:43
@Francisco-Gamino  I guess my problem is the same as this topic. 
I'm trying to Build and Test a Powershell Function locally. But when I try it, I get the message "Could not attach to process with CustomPipeName: 'AzureFunctionsPSWorker'".

When I try to run  "%AppData%\npm\func --version", It does not work.

**Comment by Francisco-Gamino** [comment] 2020-12-03 21:47
@Fabiano2 -- You can get this error for a variety of reasons. Could you please confirm that you configured your environment as described in here https://docs.microsoft.com/en-us/azure/azure-functions/create-first-function-vs-code-powershell#configure-your-environment ?

**Comment by robdmoore** [comment] 2020-12-11 09:28
Hi @Fabiano2,

I'm getting the same problem.

I have the following in `tasks.json`:

```json
    {
      "label": "startFunctionApp",
      "type": "func",
      "command": "host start --verbose",
      "problemMatcher": "$func-watch",
      "isBackground": true,
      "options": {
        "cwd": "${workspaceFolder}/function/PowerShell"
      }
```

I have the following in `launch.json`:

```json
    {
      "name": "Functions (run/debug locally)",
      "type": "PowerShell",
      "request": "attach",
      "customPipeName": "AzureFunctionsPSWorker",
      "runspaceId": 1,
      "preLaunchTask": "startFunctionApp",
      "cwd": "${workspaceFolder}/function/PowerShell"
    }
```

I have the following in `local.settings.json`:

```json
{
  "IsEncrypted": false,
  "Values": {
    "FUNCTIONS_WORKER_RUNTIME": "powershell",
    "AzureWebJobsStorage": "UseDevelopmentStorage=true",
    "FUNCTIONS_WORKER_RUNTIME_VERSION": "~7"
  }
}
```

When I execute it the function app runs and then I get the `Enter-PSHostProcess: No named pipe was found with CustomPipeName: AzureFunctionsPSWorker.` error.

I'm running:

* PS 7.1.0
* .NET Core 3.1 SDK
* .NET Core 2.2 Runtime
* VS Code 1.51.1
* PowerShell extension and Azure Functions extension
* Azure Functions Core Tools 3.0.3160
* Azure functions runtime 3.0.14916.0

**Comment by cperson** [comment] 2021-01-13 01:46
I came across this in my search and I was having the issue described. I ran `func: host start --verbose `

I noticed the terminal log got hung on a step where it's attempting to grab the latest Extensions for Azure Core tools (?). THen, I got the error described above. 

That led me to remove the `"extensionBundle": {}` block in the `hosts.json` file of my project which ultimately resolved my issue.
