### ISSUE TITLE
fan-out/fan-in pattern - Orchestrator invocated multiple times

### ISSUE THREAD

**Issue by jhauray** [Azure/azure-functions-powershell-worker#636] opened 2021-05-12 15:30 UTC
Hello,

I implemented a Durable Function with fan-out/fan-in pattern, trigger by Timer. My code contains 3 functions :
- TimerStarter : Binded with Timer and Orchestration client.
- DurableOrchestrator : Binded with orchestrationTrigger.
- ProcessActivity : Binded with activityTrigger.

PowerShell version : 7.
Runtime version : v3.
Function is hosted in a Elastic Premium Service Plan (Windows).
Timer is triggering function each hour.
Function ProcessActivity is invocated with 43 differents parameter values.

**Problem** :
When TimerStarter function trigger Orchestrator, orchestrator seem to be invocated multiple times : Log messages are repeated multiples times (see joined trace).

**Trace :**
[orchestrator.log](https://github.com/Azure/azure-functions-powershell-worker/files/6467146/orchestrator.log)

**Orchestrator Code** :

```ps1
param($Context)

$StartTime = Get-Date
$TotalNbResourcesUpdated   = 0
$TotalNbResourcesProcessed = 0

Write-Host "########## STARTING Orchestration ##########"

$ParallelTasks =
foreach ($CurrentSub in $Context.Input)
{
    Write-Host "Process activity[$($CurrentSub.Item('Name').Tostring())]"
    Invoke-ActivityFunction -FunctionName 'ProcessActivity' -Input $CurrentSub -NoWait
}

$Outputs = Wait-ActivityFunction -Task $ParallelTasks
$TotalNbResourcesUpdated = ($Outputs.NbResourcesUpdated | Measure-Object -Sum).Sum
$TotalNbResourcesProcessed = ($Outputs.NbResourcesProcessed | Measure-Object -Sum).Sum

$EndTime = Get-Date
$Duration = $EndTime - $StartTime
Write-Host "########## Orchestration FINISHED : $($Context.Input.Count) activity selected, $TotalNbResourcesProcessed resources processed, $TotalNbResourcesUpdated resources updated in $($Duration.ToString())"
```

**Questions :**
- What could explain the logs repeatition ?
- How could I be sure that activity function are not executed too many times ?
- How could I mesure duration of an orchestration ?

Thanks for your help!

**Comment by AnatoliB** [comment] 2021-05-12 22:15
@jhauray By design, Durable Orchestrator functions re-execute multiple times. The _replay_ behavior and the _event sourcing_ pattern are fundamentally important for Durable Functions. You can read more about this here:

- https://docs.microsoft.com/azure/azure-functions/durable/durable-functions-orchestrations?tabs=csharp#reliability
- https://docs.microsoft.com/azure/azure-functions/durable/durable-functions-code-constraints

This explains why you are observing these log records multiple times. Regardless of this, activity invocation are _not_ duplicated: the Durable Functions internals take care of this.

If you need to measure the duration of the entire orchestration (including all the internal restarts of the Orchestrator function), you can compare `createdTime` and `lastUpdatedTime` in the [orchestration status response](https://docs.microsoft.com/azure/azure-functions/durable/durable-functions-overview?tabs=powershell#async-http).

**Comment by AnatoliB** [comment] 2021-05-12 22:15
I hope this helps. Closing as the question is answered, but feel free to ask more questions.

**Closed as completed by AnatoliB** 2021-05-12 22:15 UTC
Labels: feature:durable functions
