### ISSUE TITLE
Using AzureAD module requires an awkward workaround

### ISSUE THREAD

**Issue by abigailbuckholdt** [Azure/azure-functions-powershell-worker#232] opened 2019-05-23 20:38 UTC
I've created a powershell function app on a consumption plan and I'm trying to use the AzureAD module in my project. I'm getting this error

```
Exception: The current processor architecture is: X86. The module 'D:\home\site\wwwroot\Modules\AzureAD\2.0.2.16\AzureAD.psd1' requires the following architecture: Amd64.
```

I've set the platform settings to 64 bit, restarted the app, and ran the following commands in a http trigger

```
[Environment]::Is64BitProcess
[Environment]::Is64BitOperatingSystem
```
and got the following output 

```
2019-05-23T20:18:23.336 [Information] OUTPUT: False
2019-05-23T20:18:23.337 [Information] OUTPUT: True
```
Is there any reason why setting the platform settings to 64 bit would not convert the platform to using a 64 bit process?

**Comment by TylerLeonhardt** [comment] 2019-05-23 22:21
This is because the PowerShell worker relies on the dotnet.exe that's available in the App Service sandbox. The dotnet.exe is always the 32bit executable. You can set your Function App to use a 64bit OS but the dotnet.exe is still 32bit.

cc @eamonoreilly @anirudhgarg The AzureAD module seems like a very good reason to speak to the App Service team about updating the dotnet.exe to the 64bit on the 64bit operating system.

**Comment by TylerLeonhardt** [comment] 2019-05-23 22:47
Actually... @abigailbuckholdt I don't think the AzureAD module works in PowerShell Core yet which is what the PowerShell worker uses...

@edyoung + @maertendMSFT : do you guys no anything about the AzureAD module working in Core?

**Comment by maertendMSFT** [comment] 2019-05-24 17:10
A preview AAD module for PowerShell is available in Azure Cloud Shell.  We are working with the module owners to update the version on the gallery after validating with partner teams.

**Comment by Matiston** [comment] 2019-05-29 12:45
@maertendMSFT, if I correct understant, Azure AAD module is already available on Azure Cloud Shell.
When you said that you are working to update the version on the gallery, does it means that the module AAD will be also available on function App ?
I have the same issue as described by @abigailbuckholdt

**Comment by mdrakiburrahman** [comment] 2019-06-09 14:20
@abigailbuckholdt I was able to connect to AzureAD via a Powershell Azure Function to get a list of users back. It wasn't easy, but here are the steps:

As @maertendMSFT mentioned above, there is a secret "preview" AzureAD module available in Azure Cloud Shell today, that's supported on x86 (since Azure Shell uses PowerShell Core). There's no way to get the x64 version of AzureAD working on Azure Function, unless Microsoft decides to support that architecture in Azure Function. Thus, we're going to be waiting until this secret preview module is available for use in Azure Function etc, which obviously will take a lot of time. I decided to get this module out of the Cloud Shell, and import it as a standard module in my function, which _is_ supported today in Azure Function (provided the module works on PowerShell Core of course)

**Step 1: Getting that Preview PowerShell module out of Cloud Shell**
To do this, I first initiated a Cloud Shell instance, which in turn created a File Share. By running the two powershell commands in the screenshot below, you're able to copy the entire Module Folder from the machine hosting Cloud Shell, and see it in the File Share.
![1](https://user-images.githubusercontent.com/46581776/59159766-6ffe9f80-8a9c-11e9-959d-8896ecefa835.png)

Then, I used Storage Explorer to download it to my local:
![2](https://user-images.githubusercontent.com/46581776/59159771-83aa0600-8a9c-11e9-823b-cbcb181229a7.png)

Which looked like this:
![3](https://user-images.githubusercontent.com/46581776/59159773-945a7c00-8a9c-11e9-96e2-1576facacd9d.png)

**Step 2: Getting the module uploaded to Azure Function, and getting it to work**
This part was really, really difficult. The thing is, I'm trying to use a Service Account to automate the task of Connect to Azure AD. But, Connect-AzureAD does not support connecting to a Service Account by using the ClientID and AppKey. You need to use a self-signed Cert and pass in the thumbprint.

This works fine and dandy on my local, but this cert based authentication feature is _not_ supported in this Preview AzureAD (you can try it on Azure Cloud Shell, it's going to return a .NETCORE error):
![7](https://user-images.githubusercontent.com/46581776/59160030-83f7d080-8a9f-11e9-84f8-ed0e3a56dd1d.png)

So - we now have the preview module that'll work on Azure Function.....but it doesn't support Cert based authentication with service principals (i.e. it's useless, since the only reason I'm building the function is to automate stuff)

So, I did a lot of digging around, and am basically doing the following to get this to work:

1. First, using Visual Studio Code, create a "Modules" folder in the root of your function directory and paste the Preview Module in:
![4](https://user-images.githubusercontent.com/46581776/59159826-3a0deb00-8a9d-11e9-931f-f77f89ce8634.png)

When you deploy to the function with VSCode, this whole folder will get uploaded to the machine hosting the Azure Function.

2. To get around the limitation with the cert based authentication limitation I mentioned, what I did in _run.ps1_ was:
-  Sign into Az module (which is available OOTB in the Azure Function)
- Extract the context token from the machine's cache
- Pass the token _into_ Connect-AzureAD, at which point I'm able to connect to my Azure AD tenant and get a list of users

Here are all the steps in a screenshot:
![5](https://user-images.githubusercontent.com/46581776/59159922-54949400-8a9e-11e9-9841-41a4745a5a96.png)

Now when I use a REST Client (I use Insomnia) to make a call to the function, I'm getting the first user in my Tenant back, via the AzureAD module:
![6](https://user-images.githubusercontent.com/46581776/59159949-aa693c00-8a9e-11e9-9a55-b647e01a6662.png)

Hope this helps! Judging by all the technical hurdles Microsoft is going to have to have to overcome (specially supporting the Cert based authentication on an unsupported .NET Core platform), I'm willing to bet it'll be some time before we see this AzureAD module functionality supported out of the box. None of this would be an issue if instead of Powershell Core, the regular 64-bit version was supported in Azure Function though....

**Comment by TylerLeonhardt** [comment] 2019-06-12 06:46
@mdrakiburrahman Windows PowerShell is available in the sandbox so you could call out to Windows PowerShell like:

```
powershell.exe -c "Import-Module AzureAD.old.one; Invoke-Something"
```

**Comment by anirudhgarg** [comment] 2019-09-27 22:34
Turns out we *do* have the 64 bit version of dotnet.exe in the Sandbox but there looks like there is a bug where-in if we change the platform to 64 bit the path *does* not change to point to the 64 bit version. We are going to look to fix it, meanwhile since we know the location of the 64 bit version of dotnet in the Sandbox we are going to see if we can first check if we are on 64 bit and invoke the 64 bit version of dotnet from the hardcoded path.

**Comment by eamonoreilly** [comment] 2019-09-30 20:46
Until we fix this, I have been putting the following code into my profile.ps1 and then using it to run the AzureAD cmdlets.

```
##Profile.ps1
##Get path to PowerShell 64bit process

$64bitPowerShellPath = Get-ChildItem -Path $Env:Windir\WinSxS -Filter PowerShell.exe -Recurse -ErrorAction SilentlyContinue | Where-Object {$_.FullName -match "amd64"}
$env:64bitPowerShellPath=$64bitPowerShellPath.VersionInfo.FileName
```

```
##Function code

$Script={
    param ()
   ##Save AzureAD module to the modules folder before publishing
    Import-Module .\modules\AzureAD
    ##Create a credential object $MyCreds and login with it.
    ##Connect-AzureAD -Credential $MyCreds
}

&$env:64bitPowerShellPath -WindowStyle Hidden -NonInteractive -Command $Script   
```

**Comment by AnatoliB** [comment] 2019-10-02 23:11
The https://github.com/Azure/azure-functions-host/pull/5011 PR resolves the problem literally stated in the title of this issue. As a result of this fix, the bitness of the PowerShell worker will match the bitness of the Host, which matches the Platform setting on the Function app (when running on the cloud). As a result, PowerShell functions will be able to use x64-only **PS Core** modules.

Unfortunately, we discovered that this will not really help AzureAD because it requires **Windows PowerShell**, and cannot work on **PowerShell Core**. In order to do that, the appropriate version of **powershell.exe** should be discovered. The bitness of the PowerShell worker process would help if Windows PowerShell followed the regular convention and could be located under either `Program Files` or `Program Files (x86)`. However, this is not the case.

So, we want to fix the PowerShell worker process bitness anyway, but the AzureAD users will have to use the workaround (to be documented).

**Comment by AnatoliB** [comment] 2019-10-02 23:28
Adding @eamonoreilly for documenting the AzureAD workaround.

**Comment by eamonoreilly** [comment] 2019-10-07 17:32
Added sample to https://github.com/eamonoreilly/ManageAzureActiveDirectoryWithPowerShellFunction for AzureAD. Will work on documentation and publish this to serverlesslibrary.net

**Comment by sunnydewangan** [comment] 2019-10-10 15:46
Hi,

Is there any ETA on fixing this issue for 64-bit dotnet.exe in the Sandbox?

**Comment by AnatoliB** [comment] 2019-10-10 17:05
The fix I mentioned (https://github.com/Azure/azure-functions-host/pull/5011) should be deployed by October 30.

@sunnydewangan Let's make sure it addresses your actual issue, though. Please be aware that the AzureAD problem is _not_ caused by the dotnet.exe bitness. The [fix](https://github.com/Azure/azure-functions-host/pull/5011) will help the situation when someone want to use **64bit-only .NET Core** code in a PowerShell functions, and I'm not aware of any complaints about this yet. If what you really need is to use the AzureAD module (or any other module that requires **Windows PowerShell** as opposed to **PowerShell Core**, you have two options:

- Wait for the AzureAD to be migrated to PS Core.
- In the meantime, use the workaround provided earlier (spawning a powershell.exe process).

**Comment by sunnydewangan** [comment] 2019-11-05 05:54
Thanks, @AnatoliB

**Comment by TylerLeonhardt** [comment] 2019-11-05 12:26
> the AzureAD problem

Side note, the Azure AD module should "just work" in PowerShell 7 so once Azure Functions adopts PowerShell 7, this scenario should be fixed

**Comment by anirudhgarg** [comment] 2019-11-05 18:16
@TylerLeonhardt is this because in PowerShell 7 we have added additional support for API's that are being used by the Azure AD module ?

**Comment by TylerLeonhardt** [comment] 2019-11-06 14:34
Correct. The Azure AD module loads Windows GUI dll which was not possible to load in PowerShell Core 6.

Of course, a Function App can't do anything with Windows GUIs so the user needs to do whatever they need to do with a "non-interactive mindset" in mind.

This also applies to the Exchange Online module and a few others.

**Comment by bwarren18** [comment] 2020-01-10 20:54
> Until we fix this, I have been putting the following code into my profile.ps1 and then using it to run the AzureAD cmdlets.
> 
> `
> ##Profile.ps1
> ##Get path to PowerShell 64bit process
> 
> $64bitPowerShellPath = Get-ChildItem -Path $Env:Windir\WinSxS -Filter PowerShell.exe -Recurse -ErrorAction SilentlyContinue | Where-Object {$_.FullName -match "amd64"}
> $env:64bitPowerShellPath=$64bitPowerShellPath.VersionInfo.FileName
> `
> 
> `
> ##Function code
> 
> $Script={
> param ()
> ##Save AzureAD module to the modules folder before publishing
> Import-Module .\modules\AzureAD
> ##Create a credential object $MyCreds and login with it.
> ##Connect-AzureAD -Credential $MyCreds
> }
> 
> &$env:64bitPowerShellPath -WindowStyle Hidden -NonInteractive -Command $Script
> `

I modified this workaround a little to improve the speed (from 13 seconds to 1).

```
$script = { Write-Output "Is 64-bit Process: $([Environment]::Is64BitProcess)" }

$PowerShell64bitPath = Get-ChildItem -Path $Env:Windir\WinSxS | Where-Object {$_.FullName -match "amd64_microsoft-windows-powershell-exe"}
$PowerShell64bitPath = Get-ChildItem -Path $PowerShell64bitPath.FullName -Filter PowerShell.exe | Select-Object -ExpandProperty FullName

Invoke-Command -ScriptBlock $script
& $PowerShell64bitPath -NoLogo -NoProfile -WindowStyle Hidden -NonInteractive -Command $Script

```

Is 64-bit Process: False
Is 64-bit Process: True

**Comment by ceylon23** [comment] 2020-04-04 21:15
> Until we fix this, I have been putting the following code into my profile.ps1 and then using it to run the AzureAD cmdlets.
> 
> `
> ##Profile.ps1
> ##Get path to PowerShell 64bit process
> 
> $64bitPowerShellPath = Get-ChildItem -Path $Env:Windir\WinSxS -Filter PowerShell.exe -Recurse -ErrorAction SilentlyContinue | Where-Object {$_.FullName -match "amd64"}
> $env:64bitPowerShellPath=$64bitPowerShellPath.VersionInfo.FileName
> `
> 
> `
> ##Function code
> 
> $Script={
> param ()
> ##Save AzureAD module to the modules folder before publishing
> Import-Module .\modules\AzureAD
> ##Create a credential object $MyCreds and login with it.
> ##Connect-AzureAD -Credential $MyCreds
> }
> 
> &$env:64bitPowerShellPath -WindowStyle Hidden -NonInteractive -Command $Script
> `

This is still the best workaround. April 4, 2020

**Comment by TylerLeonhardt** [comment] 2020-04-05 00:34
I'd also like to recommend the Microsoft Graph module that has a lot of the same functionality as the Azure AD module:

https://developer.microsoft.com/en-us/office/blogs/microsoft-graph-powershell-preview-now-on-powershell-gallery/

**Comment by AnatoliB** [comment] 2020-04-05 07:03
> I'd also like to recommend the Microsoft Graph module that has a lot of the same functionality as the Azure AD module:

Just remember about the issue and the workaround: https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/113

**Comment by wsf11** [comment] 2020-06-10 18:54
AzureAD works out of the box with Powershell 7! Import AzureAD with the `-UseWindowsPowershell` switch. 
`Import-Module AzureAD -UseWindowsPowerShell`

**Comment by JeretSB** [comment] 2020-06-22 23:21
Looking at previous comments - still unable to get things working.

@wsf11 - I got an invalid param for "-UseWindowsPowerShell" when running within my AzureFuntion.

@bwarren18 - Does your entire code go in the profile.ps1 or is it split up in some way? 

Thanks in advance!

**Comment by AnatoliB** [comment] 2020-06-22 23:28
@JeretSB "-UseWindowsPowerShell" is a PowerShell 7 feature, and Function apps use PowerShell 6 by default. In order to migrate your app to PowerShell 7, please use these instructions: https://github.com/Azure/azure-functions-powershell-worker/issues/371#issuecomment-641026259

**Comment by JeretSB** [comment] 2020-06-23 00:00
For anyone else who may stumble on this. (Until they've finished correcting this.) The following _finally_ got things working for me.

1. Setting the application to run as x64 bit: **Function App> Configuration > General Settings > Platform > 64 Bit**
2. Setting the app to run on Powershell 7 instead of 6 [on this thread](https://github.com/Azure/azure-functions-powershell-worker/issues/371#issuecomment-641026259)
3. Used: `Import-Module AzureAD -UseWindowsPowerShell`

Thanks all for the feedback. Took me a couple hours to get this working. 😔

Big thanks @AnatoliB!

EDITED: `Import-Function` replaced with `Import-Module`, as this was a typo.

**Comment by AnatoliB** [comment] 2020-06-23 02:42
I'm closing this issue as we now have a reasonable and verified way of using AzureAD.

**Closed by AnatoliB** 2020-06-23 02:42 UTC
Labels: documentation

**Comment by ebenezermakinde** [comment] 2020-07-28 13:45
This also works for MSOnline module.  Thanks for pointing me in the right direction @AnatoliB

**Comment by adriennn** [comment] 2020-11-20 13:37
Is this solution still working? When trying with the `-UseWindowsPowerShell` flag PowerShell tells me to use another flag

```powershell
 Module AzureAD is loaded in Windows PowerShell using WinPSCompatSession remoting session;
 please note that all input and output of commands from this module will be deserialized objects.
 If you want to load this module into PowerShell Core please use 'Import-Module -SkipEditionCheck' syntax
``` 

And using the other flag is causing further errors.

Moreover, it seems that Az-Connect isn't being forwarded to Windows PowerShell because if I'm trying to run a command after having used Az-Connect in profile.ps1, PowerShell warns that Az-Connect needs to be ran first.

**Comment by ebenezermakinde** [comment] 2020-11-20 14:06
> Is this solution still working? When trying with the `-UseWindowsPowerShell` flag PowerShell tells me to use another flag
> 
> ```powershell
>  Module AzureAD is loaded in Windows PowerShell using WinPSCompatSession remoting session;
>  please note that all input and output of commands from this module will be deserialized objects.
>  If you want to load this module into PowerShell Core please use 'Import-Module -SkipEditionCheck' syntax
> ```
> 
> And using the other flag is causing further errors.
> 
> Moreover, it seems that Az-Connect isn't being forwarded to Windows PowerShell because if I'm trying to run a command after having used Az-Connect in profile.ps1, PowerShell warns that Az-Connect needs to be ran first.

This is just a warning @adriennn . It just simply explains the windows compatibility feature and how it works. Because you are simply using the windows feature of Powershell. In this case, you can choose to ignore the use of that flag(SkipEditionCheck),

I hope this helps.

**Comment by adriennn** [comment] 2020-11-21 21:41
thanks @ebenezermakinde, my mistake was not to have realized AzureAD module uses its own authentication method and is entirely independent of the auth in Az module.

**Comment by regionw** [comment] 2021-03-29 17:38
Was able to load the module (apparently) using the steps provided here. However I still get error : The term 'Connect-AzureAD' is not recognized as the name of a cmdlet, function, script file, or operable program.
the function runs the Import-Module AzureAD -UserWindowsPowershell with no errors

**Comment by AnatoliB** [comment] 2021-03-29 18:36
@regionw Please note the typo: the switch name is UseWindowsPowerShell, not Use_r_WindowsPowershell

**Comment by regionw** [comment] 2021-04-02 01:12
Tks AnatoliB,

it was a typo on the question. The actual command was correct. Was getting inconsistent results, then it started working. 
Tks for answering.
