### ISSUE TITLE
Extension Bundle stopped working

### ISSUE THREAD

**Issue by mgeorgebrown89** [Azure/azure-functions-powershell-worker#212] opened 2019-05-07 18:30 UTC
Registering Azure Functions bindings for local development has stopped working for me. I had a storage tabled bound to a function and was able to pull data from it to my local environment, but now when starting the function app, I get an error message that says it isn't registered.

**Comment by daxian-dbw** [comment] 2019-05-08 00:18
Did you run `func extensions install` in the function app directory? Sharing the error message would be helpful.

**Comment by TylerLeonhardt** [comment] 2019-05-08 00:37
Cc @pragnagopa this might be a general Functions issue

**Comment by mgeorgebrown89** [comment] 2019-05-09 17:16
```
 The following 1 functions are in error:
Interactivity: The binding type(s) 'table' are not registered. Please ensure the type is correct and the binding extension is installed.
```
That's the only error I get. I'm using VSCode and the function starts up, but when I try to add a connection to a Storage account, it doesn't register anymore. I'm not sure what changed. I installed a previous version of core tools but that didn't help. My host.json file looks like this:
```
 {
    "version": "2.0",
    "extensionBundle": {
        "id": "Microsoft.Azure.Functions.ExtensionBundle",
         "version": "[1.*, 2.0.0)"
    }
}
```
I did notice that this line:
```
Looking for extension bundle Microsoft.Azure.Functions.ExtensionBundle at C:\Users\user.name\AppData\Local\Temp\Functions\ExtensionBundles\Microsoft.Azure.Functions.ExtensionBundle
```
but there's nothing actually there. Not sure if that's the issue.

**Comment by pragnagopa** [comment] 2019-05-09 17:27
@soninaren - are table bindings part of extension bundle?

**Comment by mgeorgebrown89** [comment] 2019-05-09 17:33
From what I see its part of the Microsoft.Azure.WebJobs.Extensions.Storage binding, but maybe it's not supported for PowerShell anymore? The change would have to be recent because I was _just_ doing this last week.

**Comment by soninaren** [comment] 2019-05-09 18:46
@mgeorgebrown89 can delete the folder in temp path and try again? Table binding is part of extension bundle

**Comment by soninaren** [comment] 2019-05-09 18:47
Also which version of core tools are you using?

**Comment by mgeorgebrown89** [comment] 2019-05-09 19:05
@soninaren deleted that folder and restarting the Function worked! Thanks.

Also, I was running 2.6 because I was running into some Debug-Runspace issue, but I just upgraded to 2.7.1158 and things seem to be working as expected.

**Comment by TylerLeonhardt** [comment] 2019-05-09 19:15
Thanks @soninaren for the assistance!

@mgeorgebrown89 I'll close this now since it seems like you're all set :) please let us know if you feel differently.

FYI, the Debug-Runspace issue was a regression that was fixed. 😊

**Closed by TylerLeonhardt** 2019-05-09 19:15 UTC
