### ISSUE TITLE
Error: 'No 'requirements.psd1' is found at the FunctionApp root folder: D:\home\site.'

### ISSUE THREAD

**Issue by icpenguins** [Azure/azure-functions-powershell-worker#239] opened 2019-06-04 15:45 UTC
The PowerShell function was working well a few days ago. Today I updated it, my changes being addition of comments, and now I am receiving this error message. I have made no changes to the location of the 'requirements.psd1' nor the file itself. Please fix as this is blocking.

Result: Failure
Exception: Fail to install function app dependencies. Restarting the app may resolve the error. Error: 'No 'requirements.psd1' is found at the FunctionApp root folder: D:\home\site.'
Stack:    at Microsoft.Azure.Functions.PowerShellWorker.DependencyManagement.DependencyManager.Initialize(FunctionLoadRequest request) in C:\projects\azure-functions-powershell-worker\src\DependencyManagement\DependencyManager.cs:line 179

   at Microsoft.Azure.Functions.PowerShellWorker.RequestProcessor.ProcessFunctionLoadRequest(StreamingMessage request) in C:\projects\azure-functions-powershell-worker\src\RequestProcessor.cs:line 169

**Comment by Francisco-Gamino** [comment] 2019-06-05 01:32
Hello @icpenguins , could you please verify the following?

In a function app for an HttpTrigger function, the folder structure looks like this:
```
E:\MyFunctionApp\.vscode
E:\MyFunctionApp\MyHttpTrigger
E:\MyFunctionApp\.gitignore
E:\MyFunctionApp\host.json
E:\MyFunctionApp\local.settings.json
E:\MyFunctionApp\profile.ps1
E:\MyFunctionApp\requirements.psd1
E:\MyFunctionApp\.vscode\extensions.json
E:\MyFunctionApp\MyHttpTrigger\function.json
E:\MyFunctionApp\MyHttpTrigger\run.ps1
```

At the function app root, in this case E:\MyFunctionApp, could you please verify that these files are present?
```
host.json
requirements.psd1
```

If the files are present, could you please verify the following?

1) There should be an entry for `managedDependency` in host.json
```
{
  "version": "2.0",
  "managedDependency": {
    "enabled": true
  }
}
```
2) The contents of requirements.psd1 should look like this:
```
# This file enables modules to be automatically managed by the Functions service.
# Only the Azure Az module is supported in preview.
# See https://aka.ms/functionsmanageddependency for additional information.
#
@{
    'Az' = '2.*'
}
```
Please note that your function app was created before Azure released Az version 2, then it would look like this:
```
# This file enables modules to be automatically managed by the Functions service.
# Only the Azure Az module is supported in preview.
# See https://aka.ms/functionsmanageddependency for additional information.
#
@{
    'Az' = '1.*'
}
```
Lastly, if your function app is already published, then you can get to your function app files by going to https://portal.azure.com, then navigate to your function app. Under `Platform features`, select `Advance Tools (Kudu)`. See below.

![image](https://user-images.githubusercontent.com/12720858/58923849-4ccb9d00-86f6-11e9-9b0e-54f2a9f4a189.png)

Once there, you can navigate to your files which are located under D:\home\site\wwwroot. See below.

![image](https://user-images.githubusercontent.com/12720858/58923897-800e2c00-86f6-11e9-84bc-5086ab1cbe96.png)

If you still have questions, we can setup a time to talk tomorrow. Let me know.

Cheers,
Francisco

**Comment by icpenguins** [comment] 2019-06-05 01:53
Hey Francisco,

Please note that I am using the Git deployment method to update my function. From my understanding, I have little control over where things go, correct?

Also, I don't believe that local.settings.json is required to be deployed to the site.

![2019-06-04 184357 - AzureFunc_Debug](https://user-images.githubusercontent.com/10984551/58924536-15122480-86f9-11e9-8001-972b741cc306.png)

![2019-06-04 184357 - AzureFunc_Files](https://user-images.githubusercontent.com/10984551/58924715-d29d1780-86f9-11e9-8259-ea193a7f4e2f.png)

Thoughts?

**Comment by Francisco-Gamino** [comment] 2019-06-05 17:50
Hello @icpenguins,

You are correct, local.settings.json does not get deployed with the function app. 

For deployments, we recommend using `run from package`. You can find a more information on this at  https://docs.microsoft.com/en-us/azure/azure-functions/run-functions-from-deployment-package.

Regarding your function app, everything you need seems to be there, so you should not be getting this error. Let's set up some time to talk. Are you available today at 2 pm PT?

**Comment by icpenguins** [comment] 2019-06-05 18:02
@Francisco-Gamino, I appreciate the validation. I wish I could chat at 2, but can't today; tomorrow? One thing that I noticed in the exception was that it looks like function worker process is going one directory to high (root folder: D:\home\site.') It should only go to 'D:\home\site\wwwroot'. Would you know why it is searching in a higher root folder?

**Comment by Francisco-Gamino** [comment] 2019-06-05 19:50
@icpenguins, we can try talk tomorrow. In the meantime, could you please tell the following?

1) How did you created the function app, e.g., Core Tools, VS, etc?

2) I am going to take a look at the logs for your function app. What is the time range when you got this failure? To which region did you deploy your app? Do you have the invocation id? I need the invocation id to try to figure out your function app name.

**Comment by icpenguins** [comment] 2019-06-06 01:58
@Francisco-Gamino, 

1. I created the function through VS Code
2. The time range is as current as of the posting of this response (DateTime.Now). It is hosted in 'West US 2' and I have pasted the most recent failure below which I believe has the id in it.

When I set "managedDependency": false the function runs. Unfortunately, as expected, the needed dependencies are not loaded.

**Sucess**
2019-06-06T01:42:54.550 [Information] Executing 'Functions.AzPsDynDns' (Reason='This function was programmatically called via the host APIs.', Id=e5131f8d-da95-4b39-8688-a72a11bd813f)
2019-06-06T01:42:57.653 [Information] INFORMATION: Az-Ps-Dyn-Dns HTTP trigger function called.
2019-06-06T01:42:59.507 [Information] INFORMATION: Az-Ps-Dyn-Dns HTTP trigger function completed.
2019-06-06T01:43:00.005 [Information] Executed 'Functions.AzPsDynDns' (Succeeded, Id=e5131f8d-da95-4b39-8688-a72a11bd813f)

**Failure**
2019-06-06T01:55:37.372 [Information] Executing 'Functions.AzPsDynDns' (Reason='This function was programmatically called via the host APIs.', Id=e55d8908-408d-410a-ba9c-0cf53f5b9f8c)
2019-06-06T01:55:37.903 [Error] Executed 'Functions.AzPsDynDns' (Failed, Id=e55d8908-408d-410a-ba9c-0cf53f5b9f8c)

Result: Failure
Exception: Fail to install function app dependencies. Restarting the app may resolve the error. Error: 'No 'requirements.psd1' is found at the FunctionApp root folder: D:\home\site.'
Stack:    at Microsoft.Azure.Functions.PowerShellWorker.DependencyManagement.DependencyManager.Initialize(FunctionLoadRequest request) in C:\projects\azure-functions-powershell-worker\src\DependencyManagement\DependencyManager.cs:line 179

   at Microsoft.Azure.Functions.PowerShellWorker.RequestProcessor.ProcessFunctionLoadRequest(StreamingMessage request) in C:\projects\azure-functions-powershell-worker\src\RequestProcessor.cs:line 169

**Comment by Francisco-Gamino** [comment] 2019-06-06 23:30
Hi @icpenguins,

I was able to find the logs and the info for your function app. I can see you are working with proxies. I will continue to investigate and report back. 

Quick question: Could you please confirm if your function app was working before you added the proxies code?

Thanks,
Francisco

**Comment by Francisco-Gamino** [comment] 2019-06-06 23:41
Hi @icpenguins: I was able to reproduce the issue. This is a bug on the Host (runtime) when working with proxies. I will follow up on this and provide you with an ETA for the fix in the next couple of days.

**Comment by icpenguins** [comment] 2019-06-07 23:43
@Francisco-Gamino, thanks for digging in and getting a repro. I'm looking forward to the fix ;)

**Comment by Francisco-Gamino** [comment] 2019-06-08 18:33
Here is the issue I open in the Host (runtime) https://github.com/Azure/azure-functions-host/issues/4549 to track this.

**Comment by Francisco-Gamino** [comment] 2019-06-21 04:31
@icpenguins : I will have a fix for this tomorrow. However, we need to wait for the next release of the Host (runtime) which will take about two weeks or so.

**Comment by icpenguins** [comment] 2019-06-21 16:12
@Francisco-Gamino Thank you for the update!

**Comment by bgelens** [comment] 2019-06-22 09:12
FYI, I have the same issue with profile.ps1 not found when having a proxies.json defined

```
Log-Message: No 'profile.ps1' is found at the FunctionApp root folder
```

@Francisco-Gamino I'm guessing this is the same issue but wanted to report to make sure

**Comment by TylerLeonhardt** [comment] 2019-06-23 17:42
This fixed in https://github.com/Azure/azure-functions-powershell-worker/pull/261

@bgelens that's probably related and this fix will with that too.

Just waiting on a deployment

**Comment by Francisco-Gamino** [comment] 2019-06-25 01:56
Hi @bgelens, thanks for reporting this issue. Yes, this looks related. 

I have updated the PowerShell worker in both the Core Tools (https://github.com/Azure/azure-functions-core-tools/pull/1407) and the Host (https://github.com/Azure/azure-functions-host/pull/4606).

This version of the PowerShell worker will be available in the Host (runtime) release (in about 2 weeks).

**Comment by Francisco-Gamino** [comment] 2019-07-10 21:23
Hello @icpenguins and @bgelens,--this issue is fixed in the latest version of the PowerShell worker which was release on  7/8/19. Please let me know is you see any other issues. Thanks!

**Closed by Francisco-Gamino** 2019-07-10 21:23 UTC
