### ISSUE TITLE
using module shows error in vscode, but works when debugging locally

### ISSUE THREAD

**Issue by mgeorgebrown89** [Azure/azure-functions-powershell-worker#202] opened 2019-05-02 16:24 UTC
I have a module in the Module folder at the root path of my Azure Functions App. Locally, to get these to import, I have to use the full path or a relative path. No problems there. When I debug it locally and call my function, it doesn't load it.

Since these modules are added to `$env:PSModulePath` at runtime, I can just say `using module ModuleName` and it works when I call the funciton, but VSCode highlights the line with the squiggly red underlines. 

It should be able to do something similar, but I haven't found a solution. I tried the `profile.ps1`, but no dice.

**Comment by daxian-dbw** [comment] 2019-05-05 08:12
Thanks for reporting the issue.
Yes, the module path is currently a gap in the developer experience. There needs to be a way to update the module path of the integrated powershell console when working with a PS Azure function app.

/cc @TylerLeonhardt

**Comment by joeyaiello** [comment] 2019-05-09 22:43
The solution here is to do one of two things:
* `Install-Module`/`Update-Module` and `Save-Module` so that you have the module in both your `PSModulePath` and your local function app directory
* Add the local function app `Modules` directory to process-level `PSModulePath`

Realistically, we need something like a `venv` for PowerShell that gives you a "Functions dev environment" once you enter a function app directory (e.g. `Enter/Exit-FuncEnvironment`) where you have the special types (e.g. `HttpResponseContext`), your `PSModulePath` gets the local `Modules` directory, and maybe modify your prompt to denote that you're in a session of some kind. 

Then, we could modify the VS Code extension to automatically enter that session when you open a workspace that's detected as a function app.

**Comment by eamonoreilly** [comment] 2019-09-25 21:44
Will document this and also look to add to the VS Code extension.

**Comment by andystaples** [comment] 2024-09-18 20:56
Please re-open this issue in the Functions VS Code Extension repo https://github.com/microsoft/vscode-azurefunctions/ if the issue is still present - the fix for this is to modify PSModulePath in the integrated console and the best place to do that is in the extension

**Closed by andystaples** 2024-09-18 20:56 UTC
Labels: enhancement, documentation, feature:developer experience
